/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scientificcalculator;

/**
 *
 * @author Muhammad Rifat
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        six = new java.awt.Button();
        three = new java.awt.Button();
        tan = new java.awt.Button();
        eight = new java.awt.Button();
        seven = new java.awt.Button();
        one = new java.awt.Button();
        rightParenthesis = new java.awt.Button();
        five = new java.awt.Button();
        two = new java.awt.Button();
        four = new java.awt.Button();
        zero = new java.awt.Button();
        equal = new java.awt.Button();
        dot = new java.awt.Button();
        leftParenthesis = new java.awt.Button();
        power = new java.awt.Button();
        ln = new java.awt.Button();
        ac12 = new java.awt.Button();
        cos = new java.awt.Button();
        ac14 = new java.awt.Button();
        log = new java.awt.Button();
        root = new java.awt.Button();
        pi = new java.awt.Button();
        ac = new java.awt.Button();
        sin = new java.awt.Button();
        display = new javax.swing.JTextField();
        div = new java.awt.Button();
        mul = new java.awt.Button();
        sub = new java.awt.Button();
        add = new java.awt.Button();
        percentage = new java.awt.Button();
        nine = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));

        six.setActionCommand("six");
        six.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        six.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        six.setLabel("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        three.setActionCommand("three");
        three.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        three.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        three.setLabel("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        tan.setActionCommand("tan");
        tan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tan.setLabel("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        eight.setActionCommand("eight");
        eight.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eight.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        eight.setLabel("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        seven.setActionCommand("seven");
        seven.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        seven.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        seven.setLabel("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        one.setActionCommand("one");
        one.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        one.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        one.setLabel("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        rightParenthesis.setActionCommand("rightParenthesis");
        rightParenthesis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rightParenthesis.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rightParenthesis.setLabel(")");
        rightParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightParenthesisActionPerformed(evt);
            }
        });

        five.setActionCommand("five");
        five.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        five.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        five.setLabel("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        two.setActionCommand("two");
        two.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        two.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        two.setLabel("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        four.setActionCommand("four");
        four.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        four.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        four.setLabel("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        zero.setActionCommand("zero");
        zero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        zero.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        zero.setLabel("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        equal.setActionCommand("equal");
        equal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        equal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        equal.setLabel("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        dot.setActionCommand("dot");
        dot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dot.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        dot.setLabel(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        leftParenthesis.setActionCommand("leftParenthesis");
        leftParenthesis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leftParenthesis.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        leftParenthesis.setLabel("(");
        leftParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftParenthesisActionPerformed(evt);
            }
        });

        power.setActionCommand("power");
        power.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        power.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        power.setLabel("x^");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });

        ln.setActionCommand("ln");
        ln.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ln.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ln.setLabel("ln");
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });

        ac12.setActionCommand("ans");
        ac12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ac12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ac12.setLabel("Ans");
        ac12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac12ActionPerformed(evt);
            }
        });

        cos.setActionCommand("cos");
        cos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cos.setLabel("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        ac14.setActionCommand("e");
        ac14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ac14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ac14.setLabel("e");
        ac14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac14ActionPerformed(evt);
            }
        });

        log.setActionCommand("log");
        log.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        log.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        log.setLabel("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        root.setActionCommand("root");
        root.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        root.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        root.setLabel("√");
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });

        pi.setActionCommand("pi");
        pi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        pi.setLabel("π");
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });

        ac.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ac.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ac.setLabel("AC");
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });

        sin.setActionCommand("sin");
        sin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        sin.setLabel("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        display.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        div.setActionCommand("div");
        div.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        div.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        div.setLabel("÷");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        mul.setActionCommand("mul");
        mul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mul.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        mul.setLabel("×");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        sub.setActionCommand("sub");
        sub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sub.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        sub.setLabel("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        add.setActionCommand("add");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        add.setLabel("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        percentage.setActionCommand("percentage");
        percentage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        percentage.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        percentage.setLabel("%");
        percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageActionPerformed(evt);
            }
        });

        nine.setActionCommand("nine");
        nine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nine.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nine.setLabel("9");
        nine.setName(""); // NOI18N
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sin, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ln, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(power, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pi, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(ac14, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac12, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(leftParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rightParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(one, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(percentage, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(div, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(equal, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(sub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))))
                    .addComponent(display))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leftParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rightParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(power, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ac14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ac12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        String value = display.getText() + 6;
        display.setText(value);
    }//GEN-LAST:event_sixActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        String value = display.getText() + 3;
        display.setText(value);
    }//GEN-LAST:event_threeActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        String value = display.getText() + "tan";
        display.setText(value);
    }//GEN-LAST:event_tanActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        String value = display.getText() + 8;
        display.setText(value);
    }//GEN-LAST:event_eightActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        String value = display.getText() + 7;
        display.setText(value);
    }//GEN-LAST:event_sevenActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        String value = display.getText() + 1;
        display.setText(value);
    }//GEN-LAST:event_oneActionPerformed

    private void rightParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightParenthesisActionPerformed
        String value = display.getText() + ")";
        display.setText(value);
    }//GEN-LAST:event_rightParenthesisActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        String value = display.getText() + 5;
        display.setText(value);
    }//GEN-LAST:event_fiveActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        String value = display.getText() + 2;
        display.setText(value);
    }//GEN-LAST:event_twoActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        String value = display.getText() + 4;
        display.setText(value);
    }//GEN-LAST:event_fourActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        String value = display.getText() + 0;
        display.setText(value);
    }//GEN-LAST:event_zeroActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        String inputString = display.getText();
        double value = sum(inputString);
        String outputString = Double.toString(value);
        String[] outputStringArr = outputString.split("\\.", 2);
        if(Double.parseDouble(outputStringArr[1]) > 0) {
            display.setText(outputString);
        } else {
            display.setText(outputStringArr[0]);
        }
        
        

    }//GEN-LAST:event_equalActionPerformed

    // calculation
    static double sum(String s) {
        try {
            if (s.indexOf('+') != -1) {
                String[] valueArr = s.split("[+]", 2);
                return sum(valueArr[0]) + sum(valueArr[1]);
            } else if (s.indexOf('-') != -1) {
                String[] valueArr = s.split("-", 2);
                return sum(valueArr[0]) - sum(valueArr[1]);
            } else if (s.indexOf('×') != -1) {
                String[] valueArr = s.split("×", 2);
                return sum(valueArr[0]) * sum(valueArr[1]);
            } else if (s.indexOf('÷') != -1) {
                String[] valueArr = s.split("÷", 2);
                return sum(valueArr[0]) / sum(valueArr[1]);
            } else if (s.charAt(0) == 's' && s.charAt(2) == 'n') {
                String[] valueArr = s.split("sin", 2);
                return Math.sin(Math.toRadians(sum(valueArr[1])));
            } else if (s.charAt(0) == 'c' && s.charAt(2) == 's') {
                String[] valueArr = s.split("cos", 2);
                return Math.cos(Math.toRadians(sum(valueArr[1])));
            } else if (s.charAt(0) == 't' && s.charAt(2) == 'n') {
                String[] valueArr = s.split("tan", 2);
                return Math.tan(Math.toRadians(sum(valueArr[1])));
            } else if (s.charAt(0) == 'l' && s.charAt(2) == 'g') {
                String[] valueArr = s.split("log", 2);
                return Math.log10(sum(valueArr[1]));
            }  else if (s.charAt(0) == 'l' && s.charAt(1) == 'n') {
                String[] valueArr = s.split("ln", 2);
                return Math.log(sum(valueArr[1]));
            } else if(s.indexOf('^') != -1) {
                String[] valueArr = s.split("\\^", 2);
                return Math.pow(sum(valueArr[0]), sum(valueArr[1]));
            } else if (s.charAt(0) == '√') {
                String[] valueArr = s.split("√", 2);
                return Math.sqrt(sum(valueArr[1]));
            } else {
                if(s.indexOf('π') != -1) {
                    String[] valueArr = s.split("π", 2);
                    if(valueArr[0].isEmpty() && valueArr[1].isEmpty()) {
                        return Math.PI;
                    } else if(valueArr[0].isEmpty()) {
                        return Math.PI * sum(valueArr[1]);
                    } else if(valueArr[1].isEmpty()) {
                        return Math.PI * sum(valueArr[0]);
                    } else {
                        return Math.PI * sum(valueArr[0]) * sum(valueArr[1]);
                    }
                }
            }
            return Double.parseDouble(s);

        } catch (Exception e) {
            return 0;
        }
    }

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        String value = display.getText();
        display.setText(value + '.');
    }//GEN-LAST:event_dotActionPerformed

    private void leftParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftParenthesisActionPerformed
        String value = display.getText() + "(";
        display.setText(value);
    }//GEN-LAST:event_leftParenthesisActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
        String value = display.getText() + "^";
        display.setText(value);
    }//GEN-LAST:event_powerActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        String value = display.getText() + "ln";
        display.setText(value);
    }//GEN-LAST:event_lnActionPerformed

    private void ac12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac12ActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        String value = display.getText() + "cos";
        display.setText(value);
    }//GEN-LAST:event_cosActionPerformed

    private void ac14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac14ActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        String value = display.getText() + "log";
        display.setText(value);
    }//GEN-LAST:event_logActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
        String value = display.getText() + '√';
        display.setText(value);
    }//GEN-LAST:event_rootActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        String value = display.getText() + 'π';
        display.setText(value);
    }//GEN-LAST:event_piActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        display.setText("");
    }//GEN-LAST:event_acActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        String value = display.getText() + "sin";
        display.setText(value);
    }//GEN-LAST:event_sinActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed

    }//GEN-LAST:event_displayActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        String value = display.getText() + "÷";
        display.setText(value);
    }//GEN-LAST:event_divActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        String value = display.getText() + "×";
        display.setText(value);
    }//GEN-LAST:event_mulActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        String value = display.getText() + "-";
        display.setText(value);
    }//GEN-LAST:event_subActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String value = display.getText() + "+";
        display.setText(value);
    }//GEN-LAST:event_addActionPerformed

    private void percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageActionPerformed
        String value = display.getText() + "%";
        display.setText(value);
    }//GEN-LAST:event_percentageActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        String value = display.getText() + 9;
        display.setText(value);
    }//GEN-LAST:event_nineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ac;
    private java.awt.Button ac12;
    private java.awt.Button ac14;
    private java.awt.Button add;
    private java.awt.Button cos;
    private javax.swing.JTextField display;
    private java.awt.Button div;
    private java.awt.Button dot;
    private java.awt.Button eight;
    private java.awt.Button equal;
    private java.awt.Button five;
    private java.awt.Button four;
    private java.awt.Button leftParenthesis;
    private java.awt.Button ln;
    private java.awt.Button log;
    private java.awt.Button mul;
    private java.awt.Button nine;
    private java.awt.Button one;
    private java.awt.Button percentage;
    private java.awt.Button pi;
    private java.awt.Button power;
    private java.awt.Button rightParenthesis;
    private java.awt.Button root;
    private java.awt.Button seven;
    private java.awt.Button sin;
    private java.awt.Button six;
    private java.awt.Button sub;
    private java.awt.Button tan;
    private java.awt.Button three;
    private java.awt.Button two;
    private java.awt.Button zero;
    // End of variables declaration//GEN-END:variables
}
