/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scientificcalculator;

/**
 *
 * @author Muhammad Rifat
 */
public class ScientificCalculatorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScientificCalculatorPanel
     */
    public ScientificCalculatorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        ac = new java.awt.Button();
        display = new javax.swing.JTextField();
        ac1 = new java.awt.Button();
        ac2 = new java.awt.Button();
        ac3 = new java.awt.Button();
        ac4 = new java.awt.Button();
        ac5 = new java.awt.Button();
        ac6 = new java.awt.Button();
        ac7 = new java.awt.Button();
        ac8 = new java.awt.Button();
        ac9 = new java.awt.Button();
        ac11 = new java.awt.Button();
        ac12 = new java.awt.Button();
        ac13 = new java.awt.Button();
        ac14 = new java.awt.Button();
        ac15 = new java.awt.Button();
        ac16 = new java.awt.Button();
        ac17 = new java.awt.Button();
        ac18 = new java.awt.Button();
        ac19 = new java.awt.Button();
        ac20 = new java.awt.Button();
        ac21 = new java.awt.Button();
        ac22 = new java.awt.Button();
        ac23 = new java.awt.Button();
        ac24 = new java.awt.Button();
        ac25 = new java.awt.Button();
        ac26 = new java.awt.Button();
        zero = new java.awt.Button();
        ac28 = new java.awt.Button();
        ac29 = new java.awt.Button();
        ac30 = new java.awt.Button();

        jButton1.setText("jButton1");

        jToolBar1.setRollover(true);

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(51, 51, 51));

        ac.setLabel("AC");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jButton2, org.jdesktop.beansbinding.ELProperty.create("${selected}"), ac, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ac, org.jdesktop.beansbinding.ELProperty.create("${name}"), ac, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ac, org.jdesktop.beansbinding.ObjectProperty.create(), ac, org.jdesktop.beansbinding.BeanProperty.create("name"));
        bindingGroup.addBinding(binding);

        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        ac1.setActionCommand("div");
        ac1.setLabel("/");
        ac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac1ActionPerformed(evt);
            }
        });

        ac2.setActionCommand("mul");
        ac2.setLabel("*");
        ac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac2ActionPerformed(evt);
            }
        });

        ac3.setActionCommand("sub");
        ac3.setLabel("-");
        ac3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac3ActionPerformed(evt);
            }
        });

        ac4.setActionCommand("add");
        ac4.setLabel("+");
        ac4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac4ActionPerformed(evt);
            }
        });

        ac5.setActionCommand("percentage");
        ac5.setLabel("%");
        ac5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac5ActionPerformed(evt);
            }
        });

        ac6.setActionCommand("nine");
        ac6.setLabel("9");
        ac6.setName(""); // NOI18N
        ac6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac6ActionPerformed(evt);
            }
        });

        ac7.setActionCommand("six");
        ac7.setLabel("6");
        ac7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac7ActionPerformed(evt);
            }
        });

        ac8.setActionCommand("three");
        ac8.setLabel("3");
        ac8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac8ActionPerformed(evt);
            }
        });

        ac9.setActionCommand("equal");
        ac9.setLabel("=");
        ac9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac9ActionPerformed(evt);
            }
        });

        ac11.setActionCommand("ln");
        ac11.setLabel("ln");
        ac11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac11ActionPerformed(evt);
            }
        });

        ac12.setActionCommand("ans");
        ac12.setLabel("Ans");
        ac12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac12ActionPerformed(evt);
            }
        });

        ac13.setActionCommand("cos");
        ac13.setLabel("cos");
        ac13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac13ActionPerformed(evt);
            }
        });

        ac14.setActionCommand("e");
        ac14.setLabel("e");
        ac14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac14ActionPerformed(evt);
            }
        });

        ac15.setActionCommand("log");
        ac15.setLabel("log");
        ac15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac15ActionPerformed(evt);
            }
        });

        ac16.setActionCommand("root");
        ac16.setLabel("√");
        ac16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac16ActionPerformed(evt);
            }
        });

        ac17.setActionCommand("pi");
        ac17.setLabel("π");
        ac17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac17ActionPerformed(evt);
            }
        });

        ac18.setActionCommand("sin");
        ac18.setLabel("sin");
        ac18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac18ActionPerformed(evt);
            }
        });

        ac19.setActionCommand("tan");
        ac19.setLabel("tan");
        ac19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac19ActionPerformed(evt);
            }
        });

        ac20.setActionCommand("eight");
        ac20.setLabel("8");
        ac20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac20ActionPerformed(evt);
            }
        });

        ac21.setActionCommand("seven");
        ac21.setLabel("7");
        ac21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac21ActionPerformed(evt);
            }
        });

        ac22.setActionCommand("one");
        ac22.setLabel("1");
        ac22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac22ActionPerformed(evt);
            }
        });

        ac23.setActionCommand("rightParenthesis");
        ac23.setLabel(")");
        ac23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac23ActionPerformed(evt);
            }
        });

        ac24.setActionCommand("five");
        ac24.setLabel("5");
        ac24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac24ActionPerformed(evt);
            }
        });

        ac25.setActionCommand("two");
        ac25.setLabel("2");
        ac25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac25ActionPerformed(evt);
            }
        });

        ac26.setActionCommand("four");
        ac26.setLabel("4");
        ac26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac26ActionPerformed(evt);
            }
        });

        zero.setActionCommand("zero");
        zero.setLabel("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        ac28.setActionCommand("dot");
        ac28.setLabel(".");
        ac28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac28ActionPerformed(evt);
            }
        });

        ac29.setActionCommand("leftParenthesis");
        ac29.setLabel("(");
        ac29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac29ActionPerformed(evt);
            }
        });

        ac30.setActionCommand("ln");
        ac30.setLabel("ln");
        ac30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 161, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ac15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ac11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ac30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ac17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ac26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ac24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ac21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ac29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ac23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ac20, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ac22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ac6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(ac5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ac8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ac7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(ac9, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ac26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ac22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ac19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ac30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34))
                                .addComponent(ac16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(ac14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ac12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acActionPerformed

    private void ac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac1ActionPerformed

    private void ac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac2ActionPerformed

    private void ac3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac3ActionPerformed

    private void ac4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac4ActionPerformed

    private void ac5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac5ActionPerformed

    private void ac6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac6ActionPerformed

    private void ac7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac7ActionPerformed

    private void ac8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac8ActionPerformed

    private void ac9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac9ActionPerformed

    private void ac11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac11ActionPerformed

    private void ac12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac12ActionPerformed

    private void ac13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac13ActionPerformed

    private void ac14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac14ActionPerformed

    private void ac15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac15ActionPerformed

    private void ac16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac16ActionPerformed

    private void ac17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac17ActionPerformed

    private void ac18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac18ActionPerformed

    private void ac19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac19ActionPerformed

    private void ac20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac20ActionPerformed

    private void ac21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac21ActionPerformed

    private void ac22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac22ActionPerformed

    private void ac23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac23ActionPerformed

    private void ac24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac24ActionPerformed

    private void ac25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac25ActionPerformed

    private void ac26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac26ActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        display.setText("0");
    }//GEN-LAST:event_zeroActionPerformed

    private void ac28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac28ActionPerformed

    private void ac29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac29ActionPerformed

    private void ac30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac30ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
            
    }//GEN-LAST:event_displayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ac;
    private java.awt.Button ac1;
    private java.awt.Button ac11;
    private java.awt.Button ac12;
    private java.awt.Button ac13;
    private java.awt.Button ac14;
    private java.awt.Button ac15;
    private java.awt.Button ac16;
    private java.awt.Button ac17;
    private java.awt.Button ac18;
    private java.awt.Button ac19;
    private java.awt.Button ac2;
    private java.awt.Button ac20;
    private java.awt.Button ac21;
    private java.awt.Button ac22;
    private java.awt.Button ac23;
    private java.awt.Button ac24;
    private java.awt.Button ac25;
    private java.awt.Button ac26;
    private java.awt.Button ac28;
    private java.awt.Button ac29;
    private java.awt.Button ac3;
    private java.awt.Button ac30;
    private java.awt.Button ac4;
    private java.awt.Button ac5;
    private java.awt.Button ac6;
    private java.awt.Button ac7;
    private java.awt.Button ac8;
    private java.awt.Button ac9;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Button zero;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
